// --- START BUILD SCRIPT INJECTION ZONE ---
// This array represents the dynamically generated list of artifacts.
const ARTIFACT_DATA_GENERATED = [
    { url: '././src/basel.jpg', name: 'basel (Image)' },
    { url: '././src/bunsu.jpg', name: 'bunsu (Image)' },
    { url: '././src/bunsu_02.jpg', name: 'bunsu_02 (Image)' },
    { url: '././src/chambre-jaune.jpg', name: 'chambre-jaune (Image)' },
    { url: '././src/ciudad-abierta.jpg', name: 'ciudad-abierta (Image)' },
    { url: '././src/ciudad-abierta_02.JPG', name: 'ciudad-abierta_02 (Image)' },
    { url: '././src/ciudad-abierta_03.JPG', name: 'ciudad-abierta_03 (Image)' },
    { url: '././src/ciudad-abierta_04.JPG', name: 'ciudad-abierta_04 (Image)' },
    { url: '././src/ciudad-abierta_05.jpg', name: 'ciudad-abierta_05 (Image)' },
    { url: '././src/ciudad-abierta_06.jpg', name: 'ciudad-abierta_06 (Image)' },
    { url: '././src/couvent-des-capucins_sion.jpg', name: 'couvent-des-capucins_sion (Image)' },
    { url: '././src/ernen_01.jpg', name: 'ernen_01 (Image)' },
    { url: '././src/ghga_big_6.jpeg', name: 'ghga_big_6 (Image)' },
    { url: '././src/haus_suszch.jpg', name: 'haus_suszch (Image)' },
    { url: '././src/landschaftspark-wiese_basel.JPG', name: 'landschaftspark-wiese_basel (Image)' },
    { url: '././src/liddes_01.png', name: 'liddes_01 (Image)' },
    { url: '././src/meleze_balavaux.jpg', name: 'meleze_balavaux (Image)' },
    { url: '././src/rhin_01.jpg', name: 'rhin_01 (Image)' },
    { url: '././src/rhin_02.jpg', name: 'rhin_02 (Image)' },
    { url: '././src/rhin_04.jpg', name: 'rhin_04 (Image)' },
    { url: '././src/rhin_05.jpg', name: 'rhin_05 (Image)' },
    { url: '././src/rhin_06.jpg', name: 'rhin_06 (Image)' },
    { url: '././src/rhin_07.jpg', name: 'rhin_07 (Image)' },
    { url: '././src/rhin_08.jpg', name: 'rhin_08 (Image)' },
    { url: '././src/rhin_09.jpg', name: 'rhin_09 (Image)' },
    { url: '././src/rhin_10.jpg', name: 'rhin_10 (Image)' },
    { url: '././src/rhin_11.jpg', name: 'rhin_11 (Image)' },
    { url: '././src/rhin_12.jpg', name: 'rhin_12 (Image)' },
    { url: '././src/rhin_15.png', name: 'rhin_15 (Image)' },
    { url: '././src/rouge-et-bois.jpg', name: 'rouge-et-bois (Image)' },
    { url: '././src/sandweg.JPG', name: 'sandweg (Image)' },
    { url: '././src/sept-chutes.jpg', name: 'sept-chutes (Image)' },
    { url: '././src/skogskyrkogården.jpg', name: 'skogskyrkogården (Image)' },
    { url: '././src/skogskyrkogården_02.jpg', name: 'skogskyrkogården_02 (Image)' },
    { url: '././src/taiwan_02.jpg', name: 'taiwan_02 (Image)' },
    { url: '././src/taiwan_03.jpg', name: 'taiwan_03 (Image)' },
    { url: '././src/taiwan_04.jpg', name: 'taiwan_04 (Image)' },
    { url: '././src/tempieto_poschiavo.jpg', name: 'tempieto_poschiavo (Image)' },
];
// --- END BUILD SCRIPT INJECTION ZONE ---
